<?xml version="1.0" encoding="UTF-8"?>
<!-- Archivo de construccion Ant para el cliente CONSOLA SOAP EurekaBank GR06. -->
<project name="eurekabank_soap_java_con_gr06" default="default" basedir=".">
    <description>Construye, prueba y ejecuta el cliente consola eurekabank_soap_java_con_gr06.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
