package ec.edu.monster.servicio;
import ec.edu.monster.modelo.*; import ec.edu.monster.persistencia.ConexionBD; import java.security.*; import java.sql.*; import java.time.LocalDate; import java.util.*;
public class BancoService {
  private static String sha1(String s){try{byte[] b=MessageDigest.getInstance("SHA-1").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));StringBuilder r=new StringBuilder();for(byte x:b)r.append(String.format("%02x",x));return r.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
  public boolean login(String u,String p){if(u==null||p==null)return false;try(Connection c=ConexionBD.conectar();PreparedStatement q=c.prepareStatement("SELECT vch_emplclave,vch_emplestado FROM usuario WHERE vch_emplusuario=?")){q.setString(1,u.trim());try(ResultSet r=q.executeQuery()){return r.next()&&"ACTIVO".equalsIgnoreCase(r.getString(2))&&sha1(p).equalsIgnoreCase(r.getString(1));}}catch(SQLException e){return false;}}
  public String clienteDe(String u){try(Connection c=ConexionBD.conectar();PreparedStatement q=c.prepareStatement("SELECT chr_cliecodigo FROM usuario WHERE vch_emplusuario=?")){q.setString(1,u);try(ResultSet r=q.executeQuery()){return r.next()&&r.getString(1)!=null?r.getString(1):"";}}catch(SQLException e){return "";}}
  public List<ClienteResumen> clientes(){List<ClienteResumen> a=new ArrayList<>();String s="SELECT chr_cliecodigo,chr_cliedni,vch_clienombre,vch_cliepaterno,vch_cliematerno FROM cliente ORDER BY vch_cliepaterno,vch_cliematerno,vch_clienombre";try(Connection c=ConexionBD.conectar();Statement q=c.createStatement();ResultSet r=q.executeQuery(s)){while(r.next()){ClienteResumen x=new ClienteResumen();x.setCodigo(r.getString(1));x.setDni(r.getString(2));x.setNombre((r.getString(3)+" "+r.getString(4)+" "+r.getString(5)).trim());a.add(x);}}catch(SQLException e){}return a;}
  public List<CuentaResumen> cuentas(String v){List<CuentaResumen>a=new ArrayList<>();if(v==null||v.isBlank())return a;String s="SELECT cu.chr_cuencodigo,cu.chr_monecodigo,cu.dec_cuensaldo,cu.vch_cuenestado,cl.chr_cliecodigo,cl.vch_clienombre,cl.vch_cliepaterno,cl.vch_cliematerno FROM cuenta cu JOIN cliente cl ON cl.chr_cliecodigo=cu.chr_cliecodigo WHERE cl.chr_cliecodigo=? OR cl.chr_cliedni=? ORDER BY cu.chr_cuencodigo";try(Connection c=ConexionBD.conectar();PreparedStatement q=c.prepareStatement(s)){q.setString(1,v);q.setString(2,v);try(ResultSet r=q.executeQuery()){while(r.next()){CuentaResumen x=new CuentaResumen();x.setCodigoCuenta(r.getString(1));x.setMoneda(r.getString(2));x.setSaldo(r.getDouble(3));x.setEstado(r.getString(4));x.setCodigoCliente(r.getString(5));x.setNombreCliente((r.getString(6)+" "+r.getString(7)+" "+r.getString(8)).trim());a.add(x);}}}catch(SQLException e){}return a;}
  public Resultado saldo(String n){try(Connection c=ConexionBD.conectar();PreparedStatement q=c.prepareStatement("SELECT dec_cuensaldo FROM cuenta WHERE chr_cuencodigo=?")){q.setString(1,n);try(ResultSet r=q.executeQuery()){return r.next()?Resultado.ok("Saldo consultado.",r.getDouble(1)):Resultado.error("La cuenta no existe.");}}catch(SQLException e){return Resultado.error("Error interno al consultar el saldo.");}}
  public List<MovimientoModel> movimientos(String n){List<MovimientoModel>a=new ArrayList<>();String s="SELECT m.chr_cuencodigo,m.int_movinumero,m.dtt_movifecha,m.chr_emplcodigo,m.chr_tipocodigo,m.dec_moviimporte,m.chr_cuenreferencia,m.chr_movimonori,m.dec_moviimporteori,m.dec_movitasa,t.vch_tipodescripcion FROM movimiento m JOIN tipomovimiento t ON t.chr_tipocodigo=m.chr_tipocodigo WHERE m.chr_cuencodigo=? ORDER BY m.dtt_movifecha DESC,m.int_movinumero DESC";try(Connection c=ConexionBD.conectar();PreparedStatement q=c.prepareStatement(s)){q.setString(1,n);try(ResultSet r=q.executeQuery()){while(r.next()){MovimientoModel x=new MovimientoModel();x.setCodigoCuenta(r.getString(1));x.setNumeroMovimiento(r.getInt(2));x.setFechaMovimiento(String.valueOf(r.getDate(3)));x.setCodigoEmpleado(r.getString(4));x.setCodigoTipoMovimiento(r.getString(5));x.setImporteMovimiento(r.getDouble(6));x.setCuentaReferencia(r.getString(7));x.setMonedaOrigen(r.getString(8));double z=r.getDouble(9);x.setImporteOrigen(r.wasNull()?null:z);z=r.getDouble(10);x.setTasaAplicada(r.wasNull()?null:z);x.setTipoDescripcion(r.getString(11));a.add(x);}}}catch(SQLException e){}return a;}
  private double tasa(Connection c,String o,String d)throws SQLException{if(o==null||o.equals(d))return 1;try(PreparedStatement q=c.prepareStatement("SELECT dec_tasa FROM tasacambio WHERE chr_origen=? AND chr_destino=?")){q.setString(1,o);q.setString(2,d);try(ResultSet r=q.executeQuery()){if(r.next())return r.getDouble(1);}}throw new SQLException("No hay tasa de cambio configurada de "+o+" a "+d+".");}
  private static double monto(String s){double v=Double.parseDouble(s);if(v<=0)throw new NumberFormatException();return v;}
  private CuentaModel bloquear(Connection c,String n)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT chr_monecodigo,dec_cuensaldo,vch_cuenestado FROM cuenta WHERE chr_cuencodigo=? FOR UPDATE")){q.setString(1,n);try(ResultSet r=q.executeQuery()){if(!r.next())return null;CuentaModel x=new CuentaModel();x.setCodigo(n);x.setMoneda(r.getString(1));x.setSaldo(r.getDouble(2));x.setEstado(r.getString(3));return x;}}}
  private void mov(Connection c,String n,String tipo,double imp,String ref)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO movimiento(chr_cuencodigo,int_movinumero,dtt_movifecha,chr_emplcodigo,chr_tipocodigo,dec_moviimporte,chr_cuenreferencia) VALUES(?,(SELECT COALESCE(MAX(int_movinumero),0)+1 FROM (SELECT * FROM movimiento) z WHERE chr_cuencodigo=?),?,'0001',?,?,?)")){q.setString(1,n);q.setString(2,n);q.setDate(3,java.sql.Date.valueOf(LocalDate.now()));q.setString(4,tipo);q.setDouble(5,imp);q.setString(6,ref);q.executeUpdate();}}
  private void actualizar(Connection c,String n,double d)throws SQLException{try(PreparedStatement q=c.prepareStatement("UPDATE cuenta SET dec_cuensaldo=dec_cuensaldo+?,int_cuencontmov=int_cuencontmov+1 WHERE chr_cuencodigo=?")){q.setDouble(1,d);q.setString(2,n);if(q.executeUpdate()==0)throw new SQLException();}}
  public Resultado operar(String n,String t,String moneda,boolean deposito){try(Connection c=ConexionBD.conectar()){c.setAutoCommit(false);try{double ingresado=monto(t);CuentaModel x=bloquear(c,n);if(x==null)throw new IllegalArgumentException("La cuenta no existe.");if(!"ACTIVO".equalsIgnoreCase(x.getEstado()))throw new IllegalArgumentException("La cuenta no está ACTIVA.");double v=Math.round(ingresado*tasa(c,moneda==null||moneda.isBlank()?x.getMoneda():moneda,x.getMoneda())*100d)/100d;if(!deposito&&x.getSaldo()<v)throw new IllegalArgumentException("Saldo insuficiente. Saldo actual: "+x.getSaldo());actualizar(c,n,deposito?v:-v);mov(c,n,deposito?"003":"004",v,null);c.commit();return Resultado.ok((deposito?"Depósito":"Retiro")+" realizado correctamente.",x.getSaldo()+(deposito?v:-v));}catch(Exception e){c.rollback();return Resultado.error(e instanceof IllegalArgumentException?e.getMessage():"Error interno en la operación. Se revirtieron los cambios.");}}catch(Exception e){return Resultado.error("El monto no es un número válido.");}}
  public Resultado transferir(String o,String d,String t,String moneda){if(o==null||d==null||o.equals(d))return Resultado.error("Cuenta de origen y destino requeridas.");try(Connection c=ConexionBD.conectar()){c.setAutoCommit(false);try{double entrada=monto(t);String a=o.compareTo(d)<0?o:d,b=a.equals(o)?d:o;CuentaModel ca=bloquear(c,a),cb=bloquear(c,b),or=o.equals(a)?ca:cb,de=d.equals(a)?ca:cb;if(or==null||de==null)throw new IllegalArgumentException("La cuenta de origen o destino no existe.");if(!"ACTIVO".equalsIgnoreCase(or.getEstado())||!"ACTIVO".equalsIgnoreCase(de.getEstado()))throw new IllegalArgumentException("Las cuentas deben estar ACTIVAS.");String mi=moneda==null||moneda.isBlank()?or.getMoneda():moneda;double vo=Math.round(entrada*tasa(c,mi,or.getMoneda())*100d)/100d,vd=Math.round(entrada*tasa(c,mi,de.getMoneda())*100d)/100d;if(or.getSaldo()<vo)throw new IllegalArgumentException("Saldo insuficiente. Saldo actual: "+or.getSaldo());actualizar(c,o,-vo);actualizar(c,d,vd);mov(c,o,"009",vo,d);mov(c,d,"008",vd,o);c.commit();return Resultado.ok("Transferencia de "+String.format("%.2f",entrada)+" "+mi+" de "+o+" a "+d+" realizada correctamente.",or.getSaldo()-vo);}catch(Exception e){c.rollback();return Resultado.error(e instanceof IllegalArgumentException?e.getMessage():"Error interno en la transferencia. Se revirtieron los cambios.");}}catch(Exception e){return Resultado.error("El monto no es un número válido.");}}
}
