<?xml version="1.0" encoding="UTF-8"?>
<!-- Archivo de construccion Ant para el SERVIDOR REST (JAX-RS) EurekaBank GR06. -->
<!-- Si lo borras y reabres el proyecto se volvera a crear. -->
<project name="eurekabank_restful_java_gr06" default="default" basedir=".">
    <description>Construye, prueba y despliega el servidor REST eurekabank_restful_java_gr06.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
