ms.autenticacion=http://localhost:8080/ms-autenticacion/WSLogin
ms.consulta=http://localhost:8080/ms-consulta/WSConsulta
ms.movimiento=http://localhost:8080/ms-consulta/WSMovimiento
ms.deposito=http://localhost:8080/ms-deposito/WSDeposito
ms.retiro=http://localhost:8080/ms-retiro/WSRetiro
ms.transferencia=http://localhost:8080/ms-transferencia/WSTransferencia
