<?xml version="1.0" encoding="UTF-8"?>
<!-- Archivo de construccion Ant para el cliente ESCRITORIO (Swing) REST EurekaBank GR06. -->
<project name="eurekabank_restful_java_cliesc_gr06" default="default" basedir=".">
    <description>Construye, prueba y ejecuta el cliente escritorio eurekabank_restful_java_cliesc_gr06.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
