
package ec.edu.monster.ws;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSCuenta", targetNamespace = "http://ws.monster.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCuenta {


    /**
     * 
     * @param cuenta
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSaldo", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ConsultarSaldo")
    @ResponseWrapper(localName = "consultarSaldoResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ConsultarSaldoResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/consultarSaldoRequest", output = "http://ws.monster.edu.ec/WSCuenta/consultarSaldoResponse")
    public Resultado consultarSaldo(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

    /**
     * 
     * @param cuenta
     * @param moneda
     * @param monto
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "depositar", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.Depositar")
    @ResponseWrapper(localName = "depositarResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.DepositarResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/depositarRequest", output = "http://ws.monster.edu.ec/WSCuenta/depositarResponse")
    public Resultado depositar(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda);

    /**
     * 
     * @param cuenta
     * @param moneda
     * @param monto
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retirar", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.Retirar")
    @ResponseWrapper(localName = "retirarResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.RetirarResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/retirarRequest", output = "http://ws.monster.edu.ec/WSCuenta/retirarResponse")
    public Resultado retirar(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda);

    /**
     * 
     * @param destino
     * @param moneda
     * @param monto
     * @param origen
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferir", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.Transferir")
    @ResponseWrapper(localName = "transferirResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.TransferirResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/transferirRequest", output = "http://ws.monster.edu.ec/WSCuenta/transferirResponse")
    public Resultado transferir(
        @WebParam(name = "origen", targetNamespace = "")
        String origen,
        @WebParam(name = "destino", targetNamespace = "")
        String destino,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda);

    /**
     * 
     * @param cliente
     * @return
     *     returns java.util.List<ec.edu.monster.ws.CuentaResumen>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCuentasPorCliente", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ListarCuentasPorCliente")
    @ResponseWrapper(localName = "listarCuentasPorClienteResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ListarCuentasPorClienteResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/listarCuentasPorClienteRequest", output = "http://ws.monster.edu.ec/WSCuenta/listarCuentasPorClienteResponse")
    public List<CuentaResumen> listarCuentasPorCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        String cliente);

    /**
     * 
     * @param ciudad
     * @param direccion
     * @param dni
     * @param email
     * @param materno
     * @param nombre
     * @param paterno
     * @param telefono
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarCliente", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCliente")
    @ResponseWrapper(localName = "registrarClienteResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarClienteResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/registrarClienteRequest", output = "http://ws.monster.edu.ec/WSCuenta/registrarClienteResponse")
    public Resultado registrarCliente(
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "dni", targetNamespace = "")
        String dni,
        @WebParam(name = "ciudad", targetNamespace = "")
        String ciudad,
        @WebParam(name = "direccion", targetNamespace = "")
        String direccion,
        @WebParam(name = "telefono", targetNamespace = "")
        String telefono,
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param cliente
     * @param moneda
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarCuenta", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCuenta")
    @ResponseWrapper(localName = "registrarCuentaResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCuentaResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/registrarCuentaRequest", output = "http://ws.monster.edu.ec/WSCuenta/registrarCuentaResponse")
    public Resultado registrarCuenta(
        @WebParam(name = "cliente", targetNamespace = "")
        String cliente,
        @WebParam(name = "moneda", targetNamespace = "")
        String moneda);

    /**
     * 
     * @return
     *     returns java.util.List<ec.edu.monster.ws.ClienteResumen>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarClientes", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ListarClientes")
    @ResponseWrapper(localName = "listarClientesResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ListarClientesResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/listarClientesRequest", output = "http://ws.monster.edu.ec/WSCuenta/listarClientesResponse")
    public List<ClienteResumen> listarClientes();

    /**
     * 
     * @param cuenta
     * @return
     *     returns ec.edu.monster.ws.Resultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarCuenta", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.EliminarCuenta")
    @ResponseWrapper(localName = "eliminarCuentaResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.EliminarCuentaResponse")
    @Action(input = "http://ws.monster.edu.ec/WSCuenta/eliminarCuentaRequest", output = "http://ws.monster.edu.ec/WSCuenta/eliminarCuentaResponse")
    public Resultado eliminarCuenta(
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta);

}
